
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: postgres-config-system
      path: /validate-postgres-glints-com-v1alpha1-postgresgrant
  failurePolicy: Fail
  name: vpostgresgrant.kb.io
  rules:
  - apiGroups:
    - postgres.glints.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - postgresgrants
  sideEffects: None
