
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: postgres-config-system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
