# permissions for end users to view postgrestables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgrestable-viewer-role
rules:
- apiGroups:
  - postgres.glints.com
  resources:
  - postgrestables
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.glints.com
  resources:
  - postgrestables/status
  verbs:
  - get
