# permissions for end users to view postgresgrants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresgrant-viewer-role
rules:
- apiGroups:
  - postgres.glints.com
  resources:
  - postgresgrants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.glints.com
  resources:
  - postgresgrants/status
  verbs:
  - get
