# permissions for end users to edit postgrespublications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgrespublication-editor-role
rules:
- apiGroups:
  - postgres.glints.com
  resources:
  - postgrespublications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.glints.com
  resources:
  - postgrespublications/status
  verbs:
  - get
