# permissions for end users to view postgresconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresconfig-viewer-role
rules:
- apiGroups:
  - postgres.glints.com
  resources:
  - postgresconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.glints.com
  resources:
  - postgresconfigs/status
  verbs:
  - get
