
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.glints.com
  resources:
  - postgresconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.glints.com
  resources:
  - postgresconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.glints.com
  resources:
  - postgresconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgres.glints.com
  resources:
  - postgresgrants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.glints.com
  resources:
  - postgresgrants/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.glints.com
  resources:
  - postgresgrants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgres.glints.com
  resources:
  - postgrespublications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.glints.com
  resources:
  - postgrespublications/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.glints.com
  resources:
  - postgrespublications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgres.glints.com
  resources:
  - postgrestables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.glints.com
  resources:
  - postgrestables/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.glints.com
  resources:
  - postgrestables/status
  verbs:
  - get
  - patch
  - update
