apiVersion: postgres.glints.com/v1alpha1
kind: PostgresPublication
metadata:
  name: postgrespublication-sample
spec:
  postgresRef:
    host: postgres.default
    port: 5432
    database: postgres
    secretRef:
      secretName: postgres
  name: test_publication
  tables:
  - name: test
    schema: public
  operations: []
